In [ ]:
#import the numpy library
import numpy as np

# Part 1: Dataset Creation

import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

#QUESTION 1:ARRAY DIMESNISONS
## Question 1: Array Dimensions

#the finance manager wants to confirm how many stores and product categories are present in the data.

#write NumPy code to display:

#Number of dimensions in `sales_data`
# Shape of `sales_data`
#* Total number of values
# Data type of the array
#Memory occupied by the array


#1.a>>>..number of dimesnsions in sales_data
#ndim gives the number of dimensions
print("\nNumber of dimensions in sales_data:", sales_data.ndim)

#1.b>>>..shape of sales_data
#shape gives the number of rows and columns
print("Shape of sales_data:", sales_data.shape)

#1.c>>>..total number of values
#size gives the total number of values
print("Total number of values in sales_data:", sales_data.size)

#1.d>>>..data type of the array
#dtype gives the data type of the array
print("Data type of sales_data:", sales_data.dtype)

#1.e>>>..memory occupied of the array
#nbytes gives the total memory used in bytes
print("Memory occupied by sales_data:", sales_data.nbytes, "bytes")




Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

Number of dimensions in sales_data: 2
Shape of sales_data: (5, 6)
Total number of values in sales_data: 30
Data type of sales_data: int64
Memory occupied by sales_data: 240 bytes


In [ ]:
## QUESTION 2:STORE AND CATEGORY COUNT


#calculate the following:

#Total number of stores
# Total number of product categories
# Total number of store-category combinations


#2.a>>>.. Total number of stores

total_stores = len(stores)
print("Total number of stores:", total_stores)

#2.b>>>..total number of product categories

total_categories = len(categories)
print("Total number of product categories:", total_categories)

#2.c>>>..total number of store category combination

total_combinations = total_stores * total_categories
print("Total number of store-category combinations:", total_combinations)


Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


In [ ]:
#QUESTION 3:SALES DATA TYPE CONVERSION


#The reporting application requires sales values in floating-point format.

#Convert `sales_data` into:

# `float32`
# `float64`

#compare the memory used by both arrays.

#convert sales data into float 32
sales_data_float32 = sales_data.astype('float32')

#convert sales data into float64
sales_data_float64 = sales_data.astype('float64')

#display float 32 information
print("\nfloat32 sales data:")
print(sales_data_float32)
print("Data type:", sales_data_float32.dtype)
print("Memory used:", sales_data_float32.nbytes, "bytes")

#display loat 64 information
print("\nfloat64 sales data:")
print(sales_data_float64)
print("Data type:", sales_data_float64.dtype)
print("Memory used:", sales_data_float64.nbytes, "bytes")

#compare the memory usage
print("\nMemory usage comparison:")
print("float32 memory used:", sales_data_float32.nbytes, "bytes")
print("float64 memory used:", sales_data_float64.nbytes, "bytes")

print(
    "float64 uses",
    sales_data_float64.nbytes-sales_data_float32.nbytes,
    "more bytes than float32"

)




float32 sales data:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
Data type: float32
Memory used: 120 bytes

float64 sales data:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]
Data type: float64
Memory used: 240 bytes

Memory usage comparison:
float32 memory used: 120 bytes
float64 memory used: 240 bytes
float64 uses 120 more bytes than float32


In [ ]:
#part 3:indexing and data extraction
#QUESTION 4:BENGALURU STORE ANALYSIS

#The Bengaluru regional manager wants to review sales for all product categories.
#Extract and display the complete sales row for Bengaluru.

#bengaluru is in row index 0
bengaluru_sales = sales_data[0]
print("bengaluru sales for all categories:")
print(bengaluru_sales)

bengaluru sales for all categories:
[850000 420000 310000 275000 190000 225000]


In [ ]:
## Question 5: Mumbai Cost Analysis
#Extract the total cost incurred by the Mumbai store for all product categories.

#mumbai is in row index3
mumbai_cost = cost_data[3]
print("Mumbai cost for all categories:")
print(mumbai_cost)



Mumbai cost for all categories:
[790000 390000 265000 250000 165000 205000]


In [ ]:
## Question 6: Electronics Sales Across Stores

#the electronics department wants to compare its sales performance across all five stores.

#extract the Electronics sales column from `sales_data`.

#electronics is in column index 0
electronics_sales = sales_data[:, 0]
print("Electronics sales for all stores:")
print(electronics_sales)



Electronics sales for all stores:
[ 850000  780000  920000 1050000  690000]


In [ ]:
## Question 7: Clothing Cost Across Stores

#extract the Clothing cost for every store from `cost_data`.

#clothing is in column index 2

clothing_cost=cost_data[:,2]
print("Clothing cost for all stores:")
print(clothing_cost)


Clothing cost for all stores:
[220000 210000 245000 265000 205000]


In [ ]:
# Question 8: Hyderabad Furniture Performance

#find the following for Hyderabad:

# Furniture sales, Furniture cost,Furniture profit

#hyderabad is row index 1
#furniture is column index 3
hyderabad_furniture_sales = sales_data[1, 3]
hyderabad_furniture_cost = cost_data[1, 3]

#profit=sales-cost
hyderabad_furniture_profit = hyderabad_furniture_sales - hyderabad_furniture_cost

print("Hyderabad Furniture Sales:", hyderabad_furniture_sales)
print("Hyderabad Furniture Cost:", hyderabad_furniture_cost)
print("Hyderabad Furniture Profit:", hyderabad_furniture_profit)


Hyderabad Furniture Sales: 310000
Hyderabad Furniture Cost: 225000
Hyderabad Furniture Profit: 85000


In [ ]:
## Question 9: Chennai Category Range

#Extract Chennai’s sales for the following categories:

# Groceries, Clothing, Furniture

#use array slicing.

#chennai is row index 2
#groceries,clothing and furniture are columns 1,2,3
#slice 1:4 includes 1,2,3

chennai_sales_groceries_clothing_furniture = sales_data[2, 1:4]
print("Chennai Sales for Groceries, Clothing, Furniture:")
print(chennai_sales_groceries_clothing_furniture)




Chennai Sales for Groceries, Clothing, Furniture:
[390000 340000 260000]


In [ ]:
## Question 10: Selected Store Analysis

#extract sales data for:

# Bengaluru, Chennai,Pune

#include only:

# Electronics, Clothing,Beauty,Use advanced indexing.

#store indices:
#bengaluru=0,chennai=2,pune=4

selected_store_indices = [0,2,4]

#category indices
#electronics=0
#clothing=2
#beauty=4

selected_category_indices = [0,2,4]

#np.ix_(selected_store_indices,selected_category_indices)
selected_sales = sales_data[np.ix_(selected_store_indices,selected_category_indices)]

print("Selected Stores:")
print(stores[selected_store_indices])

print("\nSelected Categories:")
print(categories[selected_category_indices])
print("\nSelected Sales:")
print(selected_sales)



Selected Stores:
['Bengaluru' 'Chennai' 'Pune']

Selected Categories:
['Electronics' 'Clothing' 'Beauty']

Selected Sales:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [ ]:
# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

#calculate the total sales revenue generated by all stores and all categories.

#calculate total sales from all stores
#and all product categories
total_sales = np.sum(sales_data)
print("Total sales revenue generated by all stores and all categories:", total_sales)




Total sales revenue generated by all stores and all categories: 11675000


In [ ]:
# Question 12: Store-Wise Sales

#Calculate total sales revenue for each store.

#Display the result together with the store names.

#Expected output format:

#text
#bengaluru: total sales,Hyderabad: total sales,Chennai: total sales,Mumbai: total sales,Pune: total sales


#axis 1 means calculate the sum across
#each row(each store)
store_wise_sales = np.sum(sales_data, axis=1)

print("store wise sales:")

#zip combines each store name
#with its corresponding total sales
for store,total in zip(stores,store_wise_sales):
    print(store,":",total)

store wise sales:
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


In [ ]:
## Question 13: Category-Wise Sales

#calculate total sales for each product category across all stores.

#display each category name with its total sales.


#axis=0 means calculate the sum down
#each column(each category)
category_wise_sales = np.sum(sales_data, axis=0)

#display each category with its total sales
for category ,total in zip(categories,category_wise_sales):
    print(category,":",total)

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


In [ ]:
## Question 14: Average Sales Per Store

#calculate the average sales generated by each store across all six product categories.

store_average_sales = np.mean(sales_data, axis=1)

print("Average sales per store:")
for store,average in zip(stores,store_average_sales):
    print(store,":",average)


Average sales per store:
Bengaluru : 378333.3333333333
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


In [ ]:
## Question 15: Average Sales Per Category

#calculate the average sales of each product category across the five stores.

#calculate average sales for every category
#across all five stores

category_average_sales = np.mean(sales_data, axis=0)

print("Average sales per category:")
for category,average in zip(categories,category_average_sales):
    print(category,":",average)


Average sales per category:
Electronics : 858000.0
Groceries : 437000.0
Clothing : 320000.0
Furniture : 283000.0
Beauty : 202000.0
Sports : 235000.0


In [ ]:
# Question 16: Highest-Selling Store

#identify:

#Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store,Use `np.argmax()`.

#find index of store with highest total sales
store_total_sales = np.sum(sales_data, axis=1)
highest_store_index = np.argmax(store_total_sales)

#get store name using index
highest_store_name = stores[highest_store_index]

#get total sales for highest store
highest_store_total_sales = store_total_sales[highest_store_index]

print("highest selling store:")
print("index",highest_store_index)
print("store name:",highest_store_name)
print("Total sales:",highest_store_total_sales)







highest selling store:
index 3
store name: Mumbai
Total sales: 2820000


In [ ]:
# Question 17: Lowest-Selling Store

#Identify the store with the lowest overall sales.

#Use `np.argmin()`.


#np.argmin returns the index
#containing the lowest value

lowest_store_index = np.argmin(store_total_sales)

#get the store name using the index
lowest_store_name = stores[lowest_store_index]

#get the total sales for the lowest store
lowest_store_total_sales = store_total_sales[lowest_store_index]

print("lowest selling store:")
print("index",lowest_store_index)
print("store name:",lowest_store_name)
print("Total sales:",lowest_store_total_sales)





lowest selling store:
index 4
store name: Pune
Total sales: 1980000


In [ ]:
## Question 18: Highest-Selling Category

# the product category that generated the highest total sales across the company.
category_total_sales = np.sum(sales_data, axis=0)
highest_category_index = np.argmax(category_total_sales)

print("highest selling category:")

print("Total sales:",category_total_sales[highest_category_index])








highest selling category:
Total sales: 4290000


In [ ]:
## Question 19: Lowest-Selling Category

#Find the product category with the lowest total sales across all stores.

## Question 19: Lowest-Selling Category

#Find the product category with the lowest total sales across all stores.


category_total_sales = np.sum(sales_data, axis=0)
lowest_category_index = np.argmin(category_total_sales)

print("lowest selling category:")

print("Total sales:",category_total_sales[lowest_category_index])


lowest selling category:
Total sales: 1010000


In [ ]:
# Part 5: Cost Analysis

## Question 20: Total Company Cost

#Calculate the total cost incurred by SmartMart across all stores and product categories.

total_cost = np.sum(cost_data)
print("Total cost incurred by SmartMart:", total_cost)



Total cost incurred by SmartMart: 8600000


In [ ]:
# Question 21: Store-Wise Cost

#Calculate the total cost incurred by each store.

store_wise_cost = np.sum(cost_data, axis=1)

print("Total cost incurred by each store:")
for store,total in zip(stores,store_wise_cost):
    print(store,":",total)


Total cost incurred by each store:
Bengaluru : 1665000
Hyderabad : 1685000
Chennai : 1710000
Mumbai : 2065000
Pune : 1475000


In [ ]:
## Question 22: Category-Wise Cost

#Calculate the total cost incurred for each product category across all stores.

category_wise_cost = np.sum(cost_data, axis=0)

print("Total cost incurred for each category:")
for category,total in zip(categories,category_wise_cost):
    print(category,":",total)

Total cost incurred for each category:
Electronics : 3250000
Groceries : 1660000
Clothing : 1145000
Furniture : 1045000
Beauty : 665000
Sports : 835000


In [ ]:
# Question 23: Most Expensive Store

#Identify the store with the highest total operating cost.

store_total_cost = np.sum(cost_data, axis=1)
most_expensive_store_index = np.argmax(store_total_cost)

print("most expensive store:",stores[most_expensive_store_index])

print("Total operating cost:",store_total_cost[most_expensive_store_index])



most expensive store: Mumbai
Total operating cost: 2065000


In [ ]:
## Question 24: Lowest-Cost Store

#Identify the store with the lowest total cost.

lowest_cost_store_index = np.argmin(store_total_cost)

print("lowest cost store:",stores[lowest_cost_store_index])

print("Total operating cost:",store_total_cost[lowest_cost_store_index])



lowest cost store: Pune
Total operating cost: 1475000


In [ ]:
## Question 25: Most Expensive Product Category

#Determine which product category has the highest total cost across all stores.

category_total_cost = np.sum(cost_data, axis=0)
most_expensive_category_index = np.argmax(category_total_cost)

print("most expensive category:",categories[most_expensive_category_index])

print("Total operating cost:",category_total_cost[most_expensive_category_index])


most expensive category: Electronics
Total operating cost: 3250000


In [ ]:
# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

#Calculate the profit generated for every store and product category.

#Use:profit_data = sales_data - cost_data,Display the complete profit matrix.

profit_data = sales_data - cost_data

print("Profit matrix:")
print(profit_data)

Profit matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
## Question 27: Store-Wise Profit

#Calculate the total profit generated by each store.

store_wise_profit = np.sum(profit_data, axis=1)

print("Total profit generated by each store:")
for store,total in zip(stores,store_wise_profit):
    print(store,":",total)



Total profit generated by each store:
Bengaluru : 605000
Hyderabad : 610000
Chennai : 600000
Mumbai : 755000
Pune : 505000


In [ ]:
## Question 28: Category-Wise Profit

#Calculate the total profit generated by each product category.

category_wise_profit = np.sum(profit_data, axis=0)

print("Total profit generated by each category:")
for category,total in zip(categories,category_wise_profit):
    print(category,":",total)



Total profit generated by each category:
Electronics : 1040000
Groceries : 525000
Clothing : 455000
Furniture : 370000
Beauty : 345000
Sports : 340000


In [ ]:
## Question 29: Most Profitable Store

#Identify the store that generated the highest total profit.

#Display:Store name, Total sales, Total cost,Total profit

store_total_sales = np.sum(sales_data, axis=1)
store_total_cost = np.sum(cost_data, axis=1)
store_total_profit = store_total_sales - store_total_cost

most_profitable_store_index = np.argmax(store_total_profit)

print("store:",stores[most_profitable_store_index])
print("total sales:",store_total_sales[most_profitable_store_index])
print("total cost:",store_total_cost[most_profitable_store_index])
print("total profit:",store_total_profit[most_profitable_store_index])


store: Mumbai
total sales: 2820000
total cost: 2065000
total profit: 755000


In [ ]:
## Question 30: Least Profitable Store

## Question 30: Least Profitable Store

store_total_profit = np.sum(profit_data, axis=1)
least_profitable_store_index = np.argmin(store_total_profit)

print("least profitable store:",stores[least_profitable_store_index])
print("total profit:",store_total_profit[least_profitable_store_index])


least profitable store: Pune
total profit: 505000


In [ ]:
## Question 31: Most Profitable Category

#Find the category with the highest total profit across all stores.

category_total_profit = np.sum(profit_data, axis=0)
most_profitable_category_index = np.argmax(category_total_profit)

print("most profitable category:",categories[most_profitable_category_index])
print("total profit:",category_total_profit[most_profitable_category_index])



most profitable category: Electronics
total profit: 1040000


In [ ]:
## Question 32: Least Profitable Category

#Find the category with the lowest total profit.

category_total_profit = np.sum(profit_data, axis=0)
least_profitable_category_index = np.argmin(category_total_profit)

print("least profitable category:",categories[least_profitable_category_index])
print("total profit:",category_total_profit[least_profitable_category_index])

least profitable category: Sports
total profit: 340000


In [ ]:
# Question 33: Maximum Individual Profit

#Find the highest profit generated by any single store-category combination.

#Display: Profit amount, Store name, Product category,Use `np.unravel_index()`.

max_profit_index = np.argmax(profit_data)
row,column = np.unravel_index(max_profit_index,profit_data.shape)

print("maximum individual profit:")
print("profit:",profit_data[row,column])
print("store:",stores[row])
print("category:",categories[column])



maximum individual profit:
profit: 260000
store: Mumbai
category: Electronics


In [ ]:
# Question 34: Minimum Individual Profit

#Find the smallest profit generated by a store-category combination.

#Display the corresponding store and category.

min_profit_index = np.argmin(profit_data)
row,column = np.unravel_index(min_profit_index,profit_data.shape)

print("minimum individual profit:")
print("profit:",profit_data[row,column])
print("minimum individual profit:",profit_data[row,column])
print("store:",stores[row])
print("category:",categories[column])

minimum individual profit:
profit: 55000
minimum individual profit: 55000
store: Pune
category: Furniture


In [ ]:
# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

#Calculate the profit margin percentage for every store-category combination.

#Use:
#profit_margin = (profit_data / sales_data) * 100

#Round the result to two decimal places.

profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)

print("Profit margin matrix:")
print(profit_margin)


Profit margin matrix:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [ ]:
## Question 36: Store-Wise Profit Margin

#Calculate the overall profit margin percentage for each store using:

#Store Profit Margin =Total Store Profit / Total Store Sales × 100

store_total_sales = np.sum(sales_data, axis=1)
store_total_profit = np.sum(profit_data, axis=1)
store_profit_margin = (store_total_profit / store_total_sales) * 100
store_profit_margin = np.round(store_profit_margin, 2)

for store,margin in zip(stores,store_profit_margin):
    print(store,":",margin,"%")

#



Bengaluru : 26.65 %
Hyderabad : 26.58 %
Chennai : 25.97 %
Mumbai : 26.77 %
Pune : 25.51 %


In [ ]:
## Question 37: Category-Wise Profit Margin

#Calculate the overall profit margin percentage for each product category.

category_total_sales = np.sum(sales_data, axis=0)
category_total_profit = np.sum(profit_data, axis=0)
category_profit_margin = (category_total_profit / category_total_sales) * 100
category_profit_margin = np.round(category_profit_margin, 2)

for category,margin in zip(categories,category_profit_margin):
    print(category,":",margin,"%")




Electronics : 24.24 %
Groceries : 24.03 %
Clothing : 28.44 %
Furniture : 26.15 %
Beauty : 34.16 %
Sports : 28.94 %


In [ ]:
## Question 38: Best Store by Profit Margin

#Identify the store with the highest overall profit margin.

best_store_index = np.argmax(store_profit_margin)

print("best store by profit margin:")
print("store:",stores[best_store_index])
print("profit margin:",store_profit_margin[best_store_index],"%")





best store by profit margin:
store: Mumbai
profit margin: 26.77 %


In [ ]:
## Question 39: Best Category by Profit Margin

#Identify the product category with the highest profit margin.

best_category_index = np.argmax(category_profit_margin)

print("best category by profit margin:")
print("category:",categories[best_category_index])
print("profit margin:",category_profit_margin[best_category_index],"%")



best category by profit margin:
category: Beauty
profit margin: 34.16 %


In [ ]:
## Question 40: Low-Margin Transactions

#Management considers a profit margin below 22% to be weak.

#Find all store-category combinations where the profit margin is below 22%.

#Display: Store, Category, Sales, Cost, Profit, Profit margin,Use Boolean indexing.

import numpy as np

# Profit calculation
profit_data = sales_data - cost_data

# Profit margin calculation
profit_margin = (profit_data / sales_data) * 100

# Find transactions where profit margin is below 22%
low_margin_indices = np.where(profit_margin < 22)

rows, columns = low_margin_indices

# Display results
for row, column in zip(rows, columns):
    print("Store:", stores[row])
    print("Category:", categories[column])
    print("Sales:", sales_data[row, column])
    print("Cost:", cost_data[row, column])
    print("Profit:", profit_data[row, column])
    print("Profit Margin:", profit_margin[row, column], "%")
    print()



In [ ]:
## Question 40: Low-Margin Transactions

#Management considers a profit margin below 22% to be weak.

#Find all store-category combinations where the profit margin is below 22%.

#Display: Store, Category, Sales, Cost, Profit, Profit margin,Use Boolean indexing.

import numpy as np

# Calculate profit
profit_data = sales_data - cost_data

# Calculate profit margin
profit_margin = (profit_data / sales_data) * 100

# Find low-margin transactions
low_margin_indices = np.where(profit_margin < 22)

rows, columns = low_margin_indices

print("LOW-MARGIN TRANSACTIONS")
print("=" * 50)

if len(rows) == 0:
    print("No transactions have profit margin below 22%.")
else:
    for row, column in zip(rows, columns):
        print("Store:", stores[row])
        print("Category:", categories[column])
        print("Sales:", sales_data[row, column])
        print("Cost:", cost_data[row, column])
        print("Profit:", profit_data[row, column])
        print("Profit Margin:", round(profit_margin[row, column], 2), "%")
        print("-" * 50)

LOW-MARGIN TRANSACTIONS
No transactions have profit margin below 22%.


In [ ]:
# Part 8: Boolean Filtering

## Question 41: High Sales Values

# Part 8: Boolean Filtering

## Question 41: High Sales Values,Find all sales values greater than ₹5,00,000.

high_sales = sales_data[sales_data > 500000]

print("High sales values:")
print(high_sales)



High sales values:
[ 850000  780000  920000 1050000  510000  690000]


In [ ]:
## Question 42: Low Sales Values

#Find all sales values below ₹2,00,000.

low_sales = sales_data[sales_data < 200000]

print("Low sales values:")
print(low_sales)


#



Low sales values:
[190000 185000 175000]


In [ ]:
## Question 43: High Profit Values

#Find all store-category combinations where profit is greater than ₹1,50,000.

rows,columns = np.where(profit_data > 150000)


for row,column in zip(rows,columns):
    print(
        "Store:",stores[row],
        "Category:",categories[column],
        "Profit:",profit_data[row,column]
    )

Store: Bengaluru Category: Electronics Profit: 210000
Store: Hyderabad Category: Electronics Profit: 190000
Store: Chennai Category: Electronics Profit: 220000
Store: Mumbai Category: Electronics Profit: 260000
Store: Pune Category: Electronics Profit: 160000


In [ ]:

## Question 44: Moderate Sales Range

#Find sales values between ₹2,50,000 and ₹5,00,000,Use `np.logical_and()`.

moderate_sales = sales_data[np.logical_and(sales_data >= 250000, sales_data <= 500000)]

print("Moderate sales values:")
print(moderate_sales)





Moderate sales values:
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [ ]:
## Question 45: Premium Performance

#A store-category combination is considered premium when:

#Sales are greater than ₹5,00,000, Profit is greater than ₹1,50,000,Find all premium-performing combinations.

premium = np.logical_and(sales_data > 500000, profit_data > 150000)

rows,columns = np.where(premium)

for row,column in zip(rows,columns):
    print(
        "Store:",stores[row],
        "Category:",categories[column],
        "Sales:",sales_data[row,column],
        "Profit:",profit_data[row,column]
    )


Store: Bengaluru Category: Electronics Sales: 850000 Profit: 210000
Store: Hyderabad Category: Electronics Sales: 780000 Profit: 190000
Store: Chennai Category: Electronics Sales: 920000 Profit: 220000
Store: Mumbai Category: Electronics Sales: 1050000 Profit: 260000
Store: Pune Category: Electronics Sales: 690000 Profit: 160000


In [ ]:
## Question 46: Underperforming Combinations

#A store-category combination is considered underperforming when:

#Sales are below ₹2,50,000, Profit margin is below 25%,Find all such combinations.


underperforming = np.logical_and(sales_data < 250000, profit_margin < 25)

rows,columns = np.where(underperforming)

for row,column in zip(rows,columns):
    print(
        "Store:",stores[row],
        "Category:",categories[column],
        "Sales:",sales_data[row,column],
        "cost:",cost_data[row,column],
        "Profit:",profit_data[row,column],
        "Profit Margin:",profit_margin[row,column],
    )

Store: Pune Category: Furniture Sales: 225000 cost: 170000 Profit: 55000 Profit Margin: 24.444444444444443


In [ ]:
## Question 47: Category Performance Classification

#Create a new array that classifies every sales value as:

# `"High"` when sales are at least ₹5,00,000
# `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
# `"Low"` when sales are below ₹2,50,000,Use `np.where()` or `np.select()`.


performance = np.select(
    [
        (sales_data >= 500000),
         np.logical_and(sales_data >= 50000,
              sales_data >= 25000,
              sales_data < 50000)
    ],
    [
        "High",
        "Medium"
    ],
    default="Low"
)
print(performance)

[['High' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium']]


In [ ]:
# Part 9: Target-Based Analysis

#Use the following category-wise monthly sales targets:

#sales_targets = np.array([
   # 800000,  # Electronics, 450000,  # Groceries,320000,  # Clothing,300000,  # Furniture,200000,  # Beauty,230000   # Sports

## Question 48: Target Comparison,Compare every store’s category sales against `sales_targets`.,Use NumPy broadcasting.

import numpy as np

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

# NumPy broadcasting
target_difference = sales_data - sales_targets

print("Target Difference:")
print(target_difference)



Target Difference:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [ ]:
## Question 49: Target Achievement Matrix

#Create a Boolean array where:

# `True` means the store achieved the category target
# `False` means the store failed to achieve the target

target_achieved = sales_data >= sales_targets

print("Target Achievement matrix:")
print(target_achieved)


Target Achievement matrix:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [ ]:
## Question 50: Target Achievement Count

#Calculate the number of categories in which each store achieved its target.

target_count = np.sum(sales_data >= sales_targets, axis=1)

for store,count in zip(stores,target_count):
    print(store,":",count,"categories achieved target")

Bengaluru : 1 categories achieved target
Hyderabad : 4 categories achieved target
Chennai : 2 categories achieved target
Mumbai : 6 categories achieved target
Pune : 0 categories achieved target


In [ ]:
## Question 51: Best Target-Performing Store

#Find the store that achieved the highest number of category targets.

best_target_index = np.argmax(target_count)

print("best target performing store:",stores[best_target_index])
print("targets achieved:",target_count[best_target_index])




best target performing store: Mumbai
targets achieved: 6


In [ ]:
## Question 52: Target Achievement by Category

#Calculate how many stores achieved the target for each product category.

category_target_count = np.sum(target_achieved,axis=0)

for category,count in zip(categories,category_target_count):
    print(category,":",count)

Electronics : 3
Groceries : 2
Clothing : 2
Furniture : 2
Beauty : 2
Sports : 2


In [ ]:
## Question 53: Sales Target Variance

#Calculate the difference between actual sales and target sales for every store.

#Use:Variance = Actual Sales - Target Sales

variance = sales_data - sales_targets

print("sales target variance:")
print(variance)

sales target variance:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [ ]:
## Question 54: Percentage Above or Below Target

#Calculate the percentage variance from the target using:
#Percentage Variance =
#(Actual Sales - Target Sales) / Target Sales × 100

percentage_variance = (sales_data - sales_targets) / sales_targets * 100

print("percentage variance from target:")
print(percentage_variance)



percentage variance from target:
[[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


In [ ]:
## Question 55: Stores Missing Electronics Target

#Identify stores that failed to achieve the Electronics sales target.
electronics_target = sales_targets[0]

missing_electronics = sales_data[:, 0] < electronics_target

print("Stores missing Electronics target:")

for store in stores[missing_electronics]:
    print(store)


Stores missing Electronics target:
Hyderabad
Pune


In [ ]:
## Question 56: Stores Achieving All Targets

#Check whether any store achieved its target in all six product categories.

#Use `np.all()`.

all_targets = np.all(target_achieved,axis=1)

print("stores achieving all targets:")

for store in stores[all_targets]:
    print(store)


stores achieving all targets:
Mumbai


In [ ]:
## Question 57: Stores Achieving At Least One Target

#Identify stores that achieved at least one category target,Use `np.any()`.

at_least_one = np.any(target_achieved,axis=1)

print("stores achieving atleast one target:")
for store in stores[at_least_one]:
    print(store)

stores achieving atleast one target:
Bengaluru
Hyderabad
Chennai
Mumbai


In [ ]:
# Part 10: Discount Scenario

#SmartMart plans to offer category-wise discounts:


#discount_rates = np.array([
    #0.10,  # Electronics: 10%
    #0.05,  # Groceries: 5%
    #0.15,  # Clothing: 15%
    #0.12,  # Furniture: 12%
   # 0.08,  # Beauty: 8%
   # 0.10   # Sports: 10%
#])

## Question 58: Discount Amount Matrix

#Calculate the discount amount for each store-category combination.

#Use broadcasting.

discount_rates = np.array([
    0.10,
    0.05,
    0.15,
    0.12,
    0.08,
    0.10,
])

discount_amount = sales_data * discount_rates

print("discount amount matrix:")
print(discount_amount)





discount amount matrix:
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [ ]:
## Question 59: Sales After Discount

#Calculate the net sales value after applying the category-wise discounts.
# Question 59: Sales After Discount

import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales data
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Discount rates
discount_rates = np.array([
    0.10,  # Electronics
    0.05,  # Groceries
    0.15,  # Clothing
    0.12,  # Furniture
    0.08,  # Beauty
    0.10   # Sports
])

# Calculate discount amount
discount_amount = sales_data * discount_rates

# Calculate sales after discount
sales_after_discount = sales_data - discount_amount

print("Sales after discount:")
print(sales_after_discount)

Sales after discount:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [ ]:
## Question 60: Profit After Discount

#Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

discount_percentage = np.array([10,5,15,8,12,10])
discount_amount = sales_data*discount_percentage/100
sales_after_discount = sales_data - discount_amount
profit_after_discount = sales_after_discount - cost_data

print("profit after discount:")
print(profit_after_discount)

profit after discount:
[[125000.  84000.  43500.  48000.  42200.  42500.]
 [112000.  87000.  40750.  60200.  44800.  46000.]
 [128000.  75500.  44000.  44200.  42800.  38500.]
 [155000.  94500.  53750.  67400.  55000.  56000.]
 [ 91000.  74750.  33000.  37000.  39000.  39500.]]


In [ ]:

## Question 61: Profit Margin After Discount

#Calculate the new profit margin after applying discounts

profit_margin_after_discount = (profit_after_discount/sales_after_discount)*100
profit_margin_after_discount = np.round(profit_margin_after_discount,2)

print("profit margin after discount:")
print(profit_margin_after_discount)


profit margin after discount:
[[16.34 21.05 16.51 18.97 25.24 20.99]
 [15.95 19.91 16.25 21.11 24.24 21.3 ]
 [15.46 20.38 15.22 18.48 26.29 19.9 ]
 [16.4  19.5  16.86 21.24 25.   21.46]
 [14.65 19.43 13.87 17.87 25.32 21.41]]


In [ ]:
## Question 62: Loss-Making Transactions

#Check whether any store-category combination becomes loss-making after discounts.

#Display the affected store and category names.

loss_making = profit_after_discount < 0
rows,columns = np.where(loss_making)

print("loss making transactions:")
if len(rows) == 0:
    print("no loss making transactions")
else:
    for row,column in zip(rows,columns):
        print(
            "store:",stores[row],
            "category:",categories[column],
            "profit after discount:",profit_after_discount[row,column]
        )



loss making transactions:
no loss making transactions


In [ ]:
## Question 63: Discount Impact

#Calculate how much total revenue the company loses because of the proposed discounts.

total_revenue_impact = np.sum(sales_data * discount_rates)

print("total_revenue lost due to discounts:",total_revenue_impact)



total_revenue lost due to discounts: 1146350.0


In [ ]:
## Question 64: Store Most Affected by Discounts

#Identify the store that loses the highest amount of revenue due to discounts.

store_discount_loss = np.sum(discount_amount,axis=1)
most_affected_index = np.argmax(store_discount_loss)

print("store most affected by discounts:",stores[most_affected_index])
print("revenue loss due to discounts:",store_discount_loss[most_affected_index])

store most affected by discounts: Mumbai
revenue loss due to discounts: 273350.0


In [ ]:
# Part 11: Tax and Price Adjustment

#The government introduces category-wise tax rates:


#tax_rates = np.array([ 0.18, 0.05, 0.12,  0.18, 0.18, 0.12])



## Question 65: Tax Collection Matrix

#Calculate the tax collected on sales for each store and category.

tax_rates = np.array([
    0.18,  # Electronics
    0.05,  # Groceries
    0.12,  # Clothing
    0.18,
    0.18,
    0.12
])
tax_collected = sales_data * tax_rates

print("tax collection matrix:")
print(tax_collected)




tax collection matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [ ]:
## Question 66: Sales Including Tax

#calculate the final customer billing value after adding tax.

sales_including_tax = sales_data + tax_collected

print("sales including tax:")
print(sales_including_tax)




sales including tax:
[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [ ]:
## Question 67: Store-Wise Tax Collection

#Calculate the total tax collected by each store.

store_wise_tax = np.sum(tax_collected,axis=1)
print("store wise tax collection:")


for store,tax in zip(stores,store_wise_tax):
    print(store,":",tax)


store wise tax collection:
Bengaluru : 321900.0
Hyderabad : 321200.0
Chennai : 331800.0
Mumbai : 401400.0
Pune : 274650.0


In [ ]:
## Question 68: Category-Wise Tax Collection

#Calculate total tax collected for each category.

category_wise_tax = np.sum(tax_collected,axis=0)

print("category wise tax collection:")
for category,tax in zip(categories,category_wise_tax):
    print(category,":",tax)




category wise tax collection:
Electronics : 772200.0
Groceries : 109250.0
Clothing : 192000.0
Furniture : 254700.0
Beauty : 181800.0
Sports : 141000.0


In [ ]:
## Question 69: Highest Tax-Contributing Store

#Identify the store that contributes the highest tax amount.

highest_tax_index = np.argmax(store_wise_tax)

print("store with highest tax:",stores[highest_tax_index])
print("highest tax amount:",store_wise_tax[highest_tax_index])


#




store with highest tax: Mumbai
highest tax amount: 401400.0


# Part 12: Array Modification

## Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.


In [ ]:
updated_sales = sales_data.copy()
updated_sales[0,0] = 740000
print("updated sales data:")
print(updated_sales)
print("original sales data:")
print(sales_data)

updated sales data:
[[ 740000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
original sales data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


## Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.


In [ ]:
updated_cost = cost_data.astype(float).copy()
updated_cost[:,4] = updated_cost[:,4] * 0.92
print("updated cost data:")
print(updated_cost)
print("original cost data:")
print(cost_data)


updated cost data:
[[640000. 315000. 220000. 205000. 115000. 160000.]
 [590000. 350000. 210000. 225000. 128800. 170000.]
 [700000. 295000. 245000. 195000. 110400. 155000.]
 [790000. 390000. 265000. 250000. 151800. 205000.]
 [530000. 310000. 205000. 170000. 105800. 145000.]]
original cost data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


## Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [ ]:
updated_furniture_cost = cost_data.astype(float).copy()
updated_furniture_cost[:,3] = updated_furniture_cost[:,3] * 1.12
print("updated furniture cost:",updated_furniture_cost[:,3])



updated furniture cost: [229600. 252000. 218400. 280000. 190400.]


## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()`.

In [ ]:
sales_without_pune = np.delete(sales_data,4,axis=0)
cost_without_pune = np.delete(cost_data,4,axis=0)

print("sales without pune:")
print(sales_without_pune)
print("cost without pune:")
print(cost_without_pune)

sales without pune:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
cost without pune:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


## Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.


In [ ]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
new_sales = np.vstack((sales_data,delhi_sales))
new_cost = np.vstack((cost_data,delhi_cost))
new_stores = np.append(stores,"Delhi")
print("updated stores:")
print(new_stores)
print("updated sales data:")
print(new_sales)
print("updated cost data:")
print(new_cost)

updated stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
updated sales data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
updated cost data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


## Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.


In [ ]:
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])
home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
new_sales = np.column_stack((sales_data,home_appliance_sales))
new_cost = np.column_stack((cost_data,home_appliance_cost))
new_categories = np.append(categories,"Home Appliances")
print("updated categories:")
print(new_categories)
print("updated sales data:")
print(new_sales)
print("updated cost data:")
print(new_cost)


updated categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']
updated sales data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
updated cost data:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


# Part 13: Sorting and Ranking

## Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [ ]:
store_total_sales = np.sum(sales_data,axis=1)
sorted_indices = np.argsort(store_total_sales)
print("stores sorted by sales:")
for index in sorted_indices:
    print(stores[index],":",store_total_sales[index])


stores sorted by sales:
Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


## Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

In [ ]:
profit_data = sales_data - cost_data
store_total_profit = np.sum(profit_data,axis=1)
rank_indices = np.argsort(store_total_profit)[::-1]
print("stores ranked by profit:")
for index in rank_indices:
    print(stores[index],":",store_total_profit[index])


stores ranked by profit:
Mumbai : 755000
Hyderabad : 610000
Bengaluru : 605000
Chennai : 600000
Pune : 505000


In [ ]:
## Question 78: Sort Categories by Revenue

#Sort product categories from highest to lowest total revenue.
category_total_sales = np.sum(sales_data,axis=0)
sorted_indices = np.argsort(category_total_sales)[::-1]
print("categories sorted by revenue:")
for index in sorted_indices:

    print(categories[index],":",category_total_sales[index])


categories sorted by revenue:
Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Sports : 1175000
Beauty : 1010000


## Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name


In [ ]:
flat_sales = sales_data.flatten()
sorted_indices = np.argsort(flat_sales)[::-1]
top_three_indices = sorted_indices[:3]
print("top three sales values:")
for index in top_three_indices:
    row,column = np.unravel_index(index,sales_data.shape)
    print(
        "sales:",flat_sales[index],
        "store:",stores[row],
        "category:",categories[column]
    )

top three sales values:
sales: 1050000 store: Mumbai category: Electronics
sales: 920000 store: Chennai category: Electronics
sales: 850000 store: Bengaluru category: Electronics


## Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.


In [ ]:
profit_data = sales_data - cost_data
flat_profit = profit_data.flatten()
sorted_indices = np.argsort(flat_profit)
bottom_three_indices = sorted_indices[:3]
print("bottom three profit values:")
for index in bottom_three_indices:
    row,column = np.unravel_index(index,profit_data.shape)
    print(
        "profit:",flat_profit[index],
        "store:",stores[row],
        "category:",categories[column]
    )


bottom three profit values:
profit: 55000 store: Pune category: Furniture
profit: 60000 store: Pune category: Sports
profit: 60000 store: Chennai category: Sports


# Part 14: Statistical Analysis

## Question 81: Sales Statistics

Calculate the following for the complete sales array:

* Minimum
* Maximum
* Mean
* Median
* Standard deviation
* Variance
* 25th percentile
* 50th percentile
* 75th percentile

In [ ]:
print("minimum sales:",np.min(sales_data))
print("maximum sales:",np.max(sales_data))
print("mean sales:",np.mean(sales_data))
print("median sales:",np.median(sales_data))
print("standard deviation sales:",np.std(sales_data))
print("variance sales:",np.var(sales_data))
print("25th percentile sales:",np.percentile(sales_data,25))
print("50th percentile sales:",np.percentile(sales_data,50))
print("75th percentile sales:",np.percentile(sales_data,75))
#

minimum sales: 175000
maximum sales: 1050000
mean sales: 389166.6666666667
median sales: 302500.0
standard deviation sales: 230322.53954448793
variance sales: 53048472222.222206
25th percentile sales: 228750.0
50th percentile sales: 302500.0
75th percentile sales: 416250.0


## Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

---

In [ ]:
store_std = np.std(sales_data,axis=1)
print("'store wise standard deviation':")
for store,std in zip(stores,store_std):
    print(store,":",std)
highest_variation_index = np.argmax(store_std)
print("store with highest variation:",stores[highest_variation_index])



'store wise standard deviation':
Bengaluru : 223059.53365762145
Hyderabad : 194502.57067709928
Chennai : 249265.58794453225
Mumbai : 271860.871280391
Pune : 177200.4514666935
store with highest variation: Mumbai


## Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.


In [ ]:
category_std = np.std(sales_data,axis=0)
print("category wise standard deviation:")
for category,std in zip(categories,category_std):
    print(category,":",std)

highest_variation_index = np.argmax(category_std)
print("category with highest variation:",categories[highest_variation_index])


category wise standard deviation:
Electronics : 122539.78945632312
Groceries : 43312.815655415434
Clothing : 33911.64991562634
Furniture : 41303.75285612677
Beauty : 26570.660511172846
Sports : 29832.867780352597
category with highest variation: Electronics


## Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.


In [ ]:
company_average = np.mean(sales_data)
above_average_count = np.sum(sales_data > company_average)
print("company average sales:",company_average)
print("number of sales above average:",above_average_count)



company average sales: 389166.6666666667
number of sales above average: 10


## Question 85: Outlier Detection

Treat any sales value greater than:

```text
Mean + 1.5 × Standard Deviation
```

as a high-value outlier.

Identify all such sales values.

In [ ]:
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

outlier_limit = mean_sales + (1.5 * std_sales)

outlier_rows, outlier_columns = np.where(
    sales_data > outlier_limit
)

print("Outlier Limit:", outlier_limit)

print("\nHigh-Value Outliers:")

for row, column in zip(
    outlier_rows,
    outlier_columns
):
    print(
        "Store:", stores[row],
        "| Category:", categories[column],
        "| Sales:", sales_data[row, column]
    )

Outlier Limit: 734650.4759833985

High-Value Outliers:
Store: Bengaluru | Category: Electronics | Sales: 850000
Store: Hyderabad | Category: Electronics | Sales: 780000
Store: Chennai | Category: Electronics | Sales: 920000
Store: Mumbai | Category: Electronics | Sales: 1050000


 Part 15: Reshaping and Transformation

## Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

* `flatten()`
* `ravel()`

Explain the difference between the two methods.


In [ ]:
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Using flatten()
flattened_sales = sales_data.flatten()

# Using ravel()
raveled_sales = sales_data.ravel()

print("Using flatten():")
print(flattened_sales)

print("\nUsing ravel():")
print(raveled_sales)

print("\nShape:")
print(flattened_sales.shape)

Using flatten():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Using ravel():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Shape:
(30,)


## Question 87: Reshape Sales Data

Reshape the `5 × 6` sales array into:

* `3 × 10`
* `10 × 3`
* `2 × 15`
* `15 × 2`

Verify that no data is lost.

---

In [ ]:
reshape_3x10 = sales_data.reshape(3, 10)
reshape_10x3 = sales_data.reshape(10, 3)
reshape_2x15 = sales_data.reshape(2, 15)
reshape_15x2 = sales_data.reshape(15, 2)

print("3 x 10:")
print(reshape_3x10)

print("\n10 x 3:")
print(reshape_10x3)

print("\n2 x 15:")
print(reshape_2x15)

print("\n15 x 2:")
print(reshape_15x2)

print("\nOriginal number of elements:", sales_data.size)
print("3x10 elements:", reshape_3x10.size)
print("10x3 elements:", reshape_10x3.size)
print("2x15 elements:", reshape_2x15.size)
print("15x2 elements:", reshape_15x2.size)

3 x 10:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]

10 x 3:
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]

2 x 15:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]

15 x 2:
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  51000

## Question 88: Transpose Sales Data

Transpose the sales array so that:

* Rows represent product categories
* Columns represent stores

Display the new shape.


In [ ]:
transposed_sales = sales_data.T
print("transposed sales:")
print(transposed_sales)
print("new shape:",transposed_sales.shape)
print("rows now represent:",categories)
print("columns now represent:",stores)

transposed sales:
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
new shape: (6, 5)
rows now represent: ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']
columns now represent: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']


## Question 89: Combined Sales and Cost Array

Stack `sales_data` and `cost_data` vertically.

Display the resulting shape.


In [ ]:
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

combined_data = np.vstack((sales_data, cost_data))

print("Combined Sales and Cost Data:")
print(combined_data)

print("\nShape:")
print(combined_data.shape)

Combined Sales and Cost Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]

Shape:
(10, 6)


## Question 90: Store-Level Combined Data

Create a three-dimensional array where:

* First layer contains sales data
* Second layer contains cost data

Use `np.stack()`.

Display the shape of the new array.

In [ ]:
combined_3d = np.stack((sales_data, cost_data))

print("Combined 3D Array:")
print(combined_3d)

print("\nShape:")
print(combined_3d.shape)

Combined 3D Array:
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]

Shape:
(2, 5, 6)


# Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

```python
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
```

## Question 91: Missing Value Detection

Find:

* Total number of missing values
* Location of missing values
* Stores and categories containing missing values

In [ ]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

missing_mask = np.isnan(sales_with_missing)

print("Total missing values:")
print(np.sum(missing_mask))

print("\nLocations of missing values:")
print(np.argwhere(missing_mask))

print("\nStores and categories containing missing values:")

rows, cols = np.where(missing_mask)

for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c])

Total missing values:
4

Locations of missing values:
[[0 2]
 [1 3]
 [3 1]
 [4 4]]

Stores and categories containing missing values:
Bengaluru - Clothing
Hyderabad - Furniture
Mumbai - Groceries
Pune - Beauty


## Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [ ]:
sales_zero = np.nan_to_num(sales_with_missing, nan=0)

print("Sales with missing values replaced with zero:")
print(sales_zero)

Sales with missing values replaced with zero:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


## Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use `np.nanmean()`.


In [ ]:
company_average = np.nanmean(sales_with_missing)

sales_with_average = np.where(
    np.isnan(sales_with_missing),
    company_average,
    sales_with_missing
)
print("Sales with missing values replaced with average:")
print(sales_with_average)

Sales with missing values replaced with average:
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


## Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

---

In [ ]:
category_average = np.nanmean(sales_with_missing, axis=0)

sales_with_category_average = np.where(
    np.isnan(sales_with_missing),
    category_average,
    sales_with_missing
)
print("Sales with missing values replaced with category average:")
print(sales_with_category_average)


Sales with missing values replaced with category average:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]



## Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

---

In [ ]:
total_before = np.sum(sales_with_missing)
total_after = np.sum(sales_zero)

print("Total sales before replacing missing values:")
print(total_before)

print("\nTotal sales after replacing missing values with zero:")
print(total_after)
print("Total sales difference:", total_before - total_after)

Total sales before replacing missing values:
nan

Total sales after replacing missing values with zero:
10370000.0
Total sales difference: nan


## Question 96: Store Performance Labels

Classify each store based on total sales:

* `"Excellent"`: Total sales above ₹28,00,000
* `"Good"`: Total sales between ₹24,00,000 and ₹28,00,000
* `"Needs Improvement"`: Total sales below ₹24,00,000


In [ ]:
import numpy as np

store_total_sales = np.sum(sales_data, axis=1)

conditions = [
    store_total_sales > 2800000,
    (store_total_sales >= 2400000) & (store_total_sales <= 2800000),
    store_total_sales < 2400000
]

labels = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

performance = np.select(
    conditions,
    labels,
    default="Unknown"
)

for store, total, label in zip(
    stores,
    store_total_sales,
    performance
):
    print(store, ":", total, ":", label)


Bengaluru : 2270000 : Needs Improvement
Hyderabad : 2295000 : Needs Improvement
Chennai : 2310000 : Needs Improvement
Mumbai : 2820000 : Excellent
Pune : 1980000 : Needs Improvement


--

## Question 97: Profitability Classification

Classify each store-category combination as:

* `"Highly Profitable"`: Profit above ₹2,00,000
* `"Profitable"`: Profit between ₹1,00,000 and ₹2,00,000
* `"Low Profit"`: Profit below ₹1,00,000
* `"Loss"`: Profit below zero


In [ ]:
profit_data = sales_data - cost_data

profitability = np.select(
    [
        profit_data < 0,
        profit_data > 200000,
        (profit_data >= 100000) & (profit_data <= 200000)
    ],
    [
        "Loss",
        "Highly Profitable",
        "Profitable"
    ],
    default="Low Profit"
)

for i in range(len(stores)):
    print("\n", stores[i])
    for j in range(len(categories)):
        print(
            categories[j],
            ":",
            profit_data[i, j],
            ":",
            profitability[i, j]
        )


 Bengaluru
Electronics : 210000 : Highly Profitable
Groceries : 105000 : Profitable
Clothing : 90000 : Low Profit
Furniture : 70000 : Low Profit
Beauty : 65000 : Low Profit
Sports : 65000 : Low Profit

 Hyderabad
Electronics : 190000 : Profitable
Groceries : 110000 : Profitable
Clothing : 85000 : Low Profit
Furniture : 85000 : Low Profit
Beauty : 70000 : Low Profit
Sports : 70000 : Low Profit

 Chennai
Electronics : 220000 : Highly Profitable
Groceries : 95000 : Low Profit
Clothing : 95000 : Low Profit
Furniture : 65000 : Low Profit
Beauty : 65000 : Low Profit
Sports : 60000 : Low Profit

 Mumbai
Electronics : 260000 : Highly Profitable
Groceries : 120000 : Profitable
Clothing : 110000 : Profitable
Furniture : 95000 : Low Profit
Beauty : 85000 : Low Profit
Sports : 85000 : Low Profit

 Pune
Electronics : 160000 : Profitable
Groceries : 95000 : Low Profit
Clothing : 75000 : Low Profit
Furniture : 55000 : Low Profit
Beauty : 60000 : Low Profit
Sports : 60000 : Low Profit


## Question 98: Expansion Recommendation

A store is eligible for expansion when:

* Total sales are above ₹25,00,000
* Total profit is above ₹7,00,000
* Overall profit margin is above 25%

Identify eligible stores.


In [ ]:
store_total_sales = np.sum(sales_data, axis=1)
store_total_profit = np.sum(profit_data, axis=1)

store_margin = (store_total_profit / store_total_sales) * 100

eligible = (
    (store_total_sales > 2500000) &
    (store_total_profit > 700000) &
    (store_margin > 25)
)

print("Stores eligible for expansion:")

for store, sales, profit, margin, is_eligible in zip(
    stores,
    store_total_sales,
    store_total_profit,
    store_margin,
    eligible
):
    if is_eligible:
        print(
            store,
            "-sales:", sales,
            "-profit:", profit,
            "-margin:", round(margin, 2), "%"
        )

Stores eligible for expansion:
Mumbai -sales: 2820000 -profit: 755000 -margin: 26.77 %


## Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

* Average sales are below ₹3,00,000
* Profit margin is above 25%

Identify the categories that satisfy these conditions.


In [ ]:
category_avg_sales = np.mean(sales_data, axis=0)

category_total_sales = np.sum(sales_data, axis=0)
category_total_profit = np.sum(profit_data, axis=0)

category_profit_margin = (
    category_total_profit / category_total_sales
) * 100

promotion = (
    (category_avg_sales < 300000) &
    (category_profit_margin > 25)
)

print("Categories recommended for additional promotion:")

for category, avg, margin, result in zip(
    categories,
    category_avg_sales,
    category_profit_margin,
    promotion
):
    if result:
        print(
            category,
            "- Average Sales:", avg,
            "- Profit Margin:", round(margin, 2), "%"
        )

Categories recommended for additional promotion:
Furniture - Average Sales: 283000.0 - Profit Margin: 26.15 %
Beauty - Average Sales: 202000.0 - Profit Margin: 34.16 %
Sports - Average Sales: 235000.0 - Profit Margin: 28.94 %


## Question 100: Cost Optimization Recommendation

Find store-category combinations where:

* Cost is greater than ₹2,50,000
* Profit margin is below 25%

These combinations should be reviewed for cost optimization.


In [ ]:
profit_margin = (profit_data / sales_data) * 100

review_mask = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

rows, cols = np.where(review_mask)

print("Store-category combinations for cost optimization:")

for r, c in zip(rows, cols):
    print(
        stores[r],
        "-",
        categories[c],
        "- Cost:", cost_data[r, c],
        "- Profit Margin:", round(profit_margin[r, c], 2), "%"
    )

Store-category combinations for cost optimization:
Bengaluru - Electronics - Cost: 640000 - Profit Margin: 24.71 %
Hyderabad - Electronics - Cost: 590000 - Profit Margin: 24.36 %
Hyderabad - Groceries - Cost: 350000 - Profit Margin: 23.91 %
Chennai - Electronics - Cost: 700000 - Profit Margin: 23.91 %
Chennai - Groceries - Cost: 295000 - Profit Margin: 24.36 %
Mumbai - Electronics - Cost: 790000 - Profit Margin: 24.76 %
Mumbai - Groceries - Cost: 390000 - Profit Margin: 23.53 %
Pune - Electronics - Cost: 530000 - Profit Margin: 23.19 %
Pune - Groceries - Cost: 310000 - Profit Margin: 23.46 %


# Part 18: Inventory Scenario

Use the following inventory arrays:

```python
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
```

## Question 101: Closing Stock

Calculate closing stock using:

```text
Closing Stock = Opening Stock - Units Sold
```


In [ ]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

closing_stock = opening_stock - units_sold

print("Closing Stock:")
print(closing_stock)

Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


## Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

---

In [ ]:
low_stock = closing_stock < 30

rows, cols = np.where(low_stock)

print("Store-category combinations with low closing stock:")

for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c], "-", closing_stock[r, c])

Store-category combinations with low closing stock:
Bengaluru - Electronics - 25
Bengaluru - Furniture - 25
Hyderabad - Electronics - 25
Hyderabad - Furniture - 25
Chennai - Electronics - 25
Chennai - Furniture - 25
Mumbai - Electronics - 25
Pune - Electronics - 25
Pune - Furniture - 20


## Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [ ]:
availability_percentage = (
    (opening_stock - units_sold) / opening_stock
) * 100

print("Stock Availability Percentage:")
for i in range(len(stores)):
    print("\n", stores[i])
    for j in range(len(categories)):
        print(
            categories[j],
            ":",
            round(availability_percentage[i, j], 2), "%"
        )
#


Stock Availability Percentage:

 Bengaluru
Electronics : 20.83 %
Groceries : 15.56 %
Clothing : 20.0 %
Furniture : 27.78 %
Beauty : 24.0 %
Sports : 22.22 %

 Hyderabad
Electronics : 22.73 %
Groceries : 16.0 %
Clothing : 17.86 %
Furniture : 25.0 %
Beauty : 22.22 %
Sports : 22.5 %

 Chennai
Electronics : 19.23 %
Groceries : 16.67 %
Clothing : 15.62 %
Furniture : 29.41 %
Beauty : 25.0 %
Sports : 23.53 %

 Mumbai
Electronics : 16.67 %
Groceries : 14.55 %
Clothing : 15.71 %
Furniture : 25.0 %
Beauty : 21.67 %
Sports : 20.45 %

 Pune
Electronics : 25.0 %
Groceries : 17.5 %
Clothing : 21.15 %
Furniture : 26.67 %
Beauty : 25.0 %
Sports : 25.0 %


## Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.


In [ ]:
sold_percentage = (units_sold / opening_stock) * 100

fast_moving = sold_percentage > 80
rows,cols = np.where(fast_moving)

print("Fast-moving store-category combinations:")

for r, c in zip(rows, cols):
    print(stores[r], "-", categories[c], "-", sold_percentage[r, c], "%")

Fast-moving store-category combinations:
Bengaluru - Groceries - 84.44444444444444 %
Hyderabad - Groceries - 84.0 %
Hyderabad - Clothing - 82.14285714285714 %
Chennai - Electronics - 80.76923076923077 %
Chennai - Groceries - 83.33333333333334 %
Chennai - Clothing - 84.375 %
Mumbai - Electronics - 83.33333333333334 %
Mumbai - Groceries - 85.45454545454545 %
Mumbai - Clothing - 84.28571428571429 %
Pune - Groceries - 82.5 %


## Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.




In [ ]:
catgory_units_sold = np.sum(units_sold, axis=0)
print("category wise units sold:")
for category, units in zip(categories, catgory_units_sold):
    print(category, ":", units)

category wise units sold:
Electronics : 485
Groceries : 1950
Clothing : 1240
Furniture : 345
Beauty : 980
Sports : 720


## Question 106: Store-Wise Units Sold

Calculate total units sold by each store.


In [ ]:
store_units_sold = np.sum(units_sold, axis=1)
print("Store wise units sold:")
for store, units in zip(stores, store_units_sold):
    print(store, ":", units)


Store wise units sold:
Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


## Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

---


In [ ]:
store_units_sold = np.sum(units_sold, axis=1)

best_store_index = np.argmax(store_units_sold)
best_store = stores[best_store_index]
print("best store by unit sales:")
print(best_store)

print("Best-selling store:", best_store)


best store by unit sales:
Mumbai
Best-selling store: Mumbai



## Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.


In [ ]:
reorder_matrix = closing_stock < 25
print("Reorder boolean matrix:")
print(reorder_matrix)

Reorder boolean matrix:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


## Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.


In [ ]:
reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)
print("Reorder Quantity:")
print(reorder_quantity)

Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# Part 19: Advanced NumPy Questions

## Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using `np.cumsum()`.


In [ ]:
cumulative_sales = np.cumsum(sales_data, axis=1)
print("Cumulative Store Sales:")
print(cumulative_sales)
for store, values in zip(stores, cumulative_sales):
    print(store, ":", values)

Cumulative Store Sales:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]
Bengaluru : [ 850000 1270000 1580000 1855000 2045000 2270000]
Hyderabad : [ 780000 1240000 1535000 1845000 2055000 2295000]
Chennai : [ 920000 1310000 1650000 1910000 2095000 2310000]
Mumbai : [1050000 1560000 1935000 2280000 2530000 2820000]
Pune : [ 690000 1095000 1375000 1600000 1775000 1980000]


## Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.


In [ ]:
flat_sales = sales_data.flatten()
cumulative_sales = np.cumsum(flat_sales)
print("Cumulative Company Sales:")
print(cumulative_sales)

Cumulative Company Sales:
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


## Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using `np.diff()`.

In [ ]:
sales_difference = np.diff(sales_data, axis=1)
print("Sales Difference Between Categories:")
print(sales_difference)


Sales Difference Between Categories:
[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


## Question 113: Unique Sales Values

Find all unique sales values in `sales_data`.

Also count the frequency of each value.

In [ ]:
unique_sales, frequency = np.unique(
    sales_data,
    return_counts=True
)

print("\nQ113: Unique Sales Values and Frequency")

for value, count in zip(unique_sales, frequency):
    print(value, ":", count)





Q113: Unique Sales Values and Frequency
175000 : 1
185000 : 1
190000 : 1
205000 : 1
210000 : 1
215000 : 1
225000 : 2
240000 : 1
250000 : 1
260000 : 1
275000 : 1
280000 : 1
290000 : 1
295000 : 1
310000 : 2
340000 : 1
345000 : 1
375000 : 1
390000 : 1
405000 : 1
420000 : 1
460000 : 1
510000 : 1
690000 : 1
780000 : 1
850000 : 1
920000 : 1
1050000 : 1


## Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [ ]:
search_value = 420000
locations = np.argwhere(sales_data == search_value)
print("search_for_420000")
if locations.size > 0:
    print("420000 exists in sales_data.")
    print("locations(row,column:")
    print(locations)
    for row,column in locations:
        print(
            stores[row],
            "-",
            categories[column],
            ":",
            sales_data[row,column]
        )
else:
    print("420000 does not exist in sales_data.")


search_for_420000
420000 exists in sales_data.
locations(row,column:
[[0 1]]
Bengaluru - Groceries : 420000


## Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using `np.all()`.

## Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

* Minimum: ₹75,000
* Maximum: ₹2,50,000

Use `np.clip()` to create a reporting profit array.


In [9]:
profit_data = sales_data - cost_data
reporting = np.clip(profit_data, 75000, 250000)
print("Profit data:",profit_data)
print("Reporting:",reporting)

Profit data: [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]
Reporting: [[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


## Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

```text
Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)
```

In [8]:
max_sales = np.max(sales_data)
min_sales = np.min(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("minimum sales:",min_sales)
print("maximum sales:",max_sales)
print("normalized sales:",normalized_sales)

minimum sales: 175000
maximum sales: 1050000
normalized sales: [[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


## Question 118: Standardize Sales Data

Standardize sales using:

```text
Standardized Sales =
(Sales - Mean Sales) / Standard Deviation
```

In [7]:
mean_sales = np.mean(sales_data)
standard_deviation = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / standard_deviation
print("mean sales:", mean_sales)
print("standard deviation:", standard_deviation)
print("standardized sales:", standardized_sales)

mean sales: 389166.6666666667
standard deviation: 230322.53954448793
standardized sales: [[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


## Question 119: Round Values

Convert profit margin values into:

* Two decimal places
* Nearest whole number
* Floor values
* Ceiling values

In [6]:

total_sales = np.sum(sales_data, axis = 1)
profit_data = sales_data - cost_data
total_profit = np.sum(profit_data, axis=1)
profit_margin = (total_sales / total_profit) * 100
two_decimal = np.round(profit_margin, 2)
nearest_whole_num = np.round(profit_margin)
floor_val = np.floor(profit_margin)
ceil_val = np.ceil(profit_margin)
print(two_decimal)
print(nearest_whole_num)
print(floor_val)
print(ceil_val)




[375.21 376.23 385.   373.51 392.08]
[375. 376. 385. 374. 392.]
[375. 376. 385. 373. 392.]
[376. 377. 385. 374. 393.]


## Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

* `sales_data.npy`
* `cost_data.npy`
* `profit_data.npy`

Load them back and verify that the loaded arrays are equal to the original arrays.

---

# Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

## Company Summary

1. Total company sales
2. Total company cost
3. Total company profit
4. Overall company profit margin
5. Average transaction value
6. Highest individual sales value
7. Lowest individual sales value

## Store Summary

For every store, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Number of category targets achieved
6. Total units sold
7. Expansion eligibility

## Category Summary

For every category, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Average sales
6. Number of stores achieving the target
7. Total units sold

## Management Recommendations

Based on the analysis, identify:

1. Best-performing store
2. Lowest-performing store
3. Most profitable category
4. Lowest-profit category
5. Store recommended for expansion
6. Category requiring additional marketing
7. Store-category combinations needing cost optimization
8. Store-category combinations requiring inventory reorder

---

# Expected Final Output Format

```text
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:
```


In [ ]:
import numpy as np

# ============================================================
# SMARTMART RETAIL ANALYTICS PROJECT
# ============================================================

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])


# ============================================================
# PROFIT
# ============================================================

profit_data = sales_data - cost_data


# ============================================================
# EXAMPLE TARGETS
# Replace with your assignment's exact targets if provided
# ============================================================

sales_targets = np.array([
    800000,
    400000,
    300000,
    250000,
    180000,
    220000
])


# ============================================================
# EXAMPLE UNITS SOLD
# Replace with your assignment's exact units data if provided
# ============================================================

units_sold = np.array([
    [850, 420, 310, 275, 190, 225],
    [780, 460, 295, 310, 210, 240],
    [920, 390, 340, 260, 185, 215],
    [1050, 510, 375, 345, 250, 290],
    [690, 405, 280, 225, 175, 205]
])


# ============================================================
# EXAMPLE INVENTORY DATA
# ============================================================

closing_stock = np.array([
    [80, 150, 120, 90, 110, 95],
    [75, 140, 130, 85, 105, 90],
    [60, 125, 115, 70, 95, 85],
    [55, 100, 90, 65, 80, 75],
    [70, 135, 125, 80, 100, 90]
])

reorder_level = 100


# ============================================================
# COMPANY SUMMARY
# ============================================================

total_company_sales = np.sum(sales_data)
total_company_cost = np.sum(cost_data)
total_company_profit = np.sum(profit_data)

overall_margin = (
    total_company_profit
    / total_company_sales
) * 100

average_transaction_value = np.mean(sales_data)
highest_sales = np.max(sales_data)
lowest_sales = np.min(sales_data)


print("\n")
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")

print("\nCOMPANY SUMMARY")
print("---------------")
print("Total Sales:", total_company_sales)
print("Total Cost:", total_company_cost)
print("Total Profit:", total_company_profit)
print("Overall Profit Margin:", round(overall_margin, 2), "%")
print("Average Transaction Value:", round(average_transaction_value, 2))
print("Highest Individual Sales Value:", highest_sales)
print("Lowest Individual Sales Value:", lowest_sales)


# ============================================================
# STORE SUMMARY
# ============================================================

store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

store_margin = (
    store_profit
    / store_sales
) * 100

target_achieved = sales_data >= sales_targets

number_targets_achieved = np.sum(
    target_achieved,
    axis=1
)

total_units_store = np.sum(
    units_sold,
    axis=1
)

# Expansion criteria:
# Sales > 2,500,000
# Profit > 700,000
# Margin > 25%

eligible_for_expansion = (
    (store_sales > 2500000)
    &
    (store_profit > 700000)
    &
    (store_margin > 25)
)


print("\nSTORE SUMMARY")
print("-------------")

for i in range(len(stores)):
    print("\nStore:", stores[i])
    print("Total Sales:", store_sales[i])
    print("Total Cost:", store_cost[i])
    print("Total Profit:", store_profit[i])
    print("Profit Margin:", round(store_margin[i], 2), "%")
    print(
        "Category Targets Achieved:",
        number_targets_achieved[i]
    )
    print("Total Units Sold:", total_units_store[i])
    print(
        "Expansion Eligibility:",
        "Eligible" if eligible_for_expansion[i]
        else "Not Eligible"
    )


# ============================================================
# CATEGORY SUMMARY
# ============================================================

category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

category_margin = (
    category_profit
    / category_sales
) * 100

category_average_sales = np.mean(
    sales_data,
    axis=0
)

category_targets_achieved = np.sum(
    sales_data >= sales_targets,
    axis=0
)

category_units = np.sum(
    units_sold,
    axis=0
)


print("\nCATEGORY SUMMARY")
print("----------------")

for i in range(len(categories)):
    print("\nCategory:", categories[i])
    print("Total Sales:", category_sales[i])
    print("Total Cost:", category_cost[i])
    print("Total Profit:", category_profit[i])
    print("Profit Margin:", round(category_margin[i], 2), "%")
    print("Average Sales:", round(category_average_sales[i], 2))
    print(
        "Stores Achieving Target:",
        category_targets_achieved[i]
    )
    print("Total Units Sold:", category_units[i])


# ============================================================
# MANAGEMENT RECOMMENDATIONS
# ============================================================

# Best and lowest-performing stores based on profit
best_store_index = np.argmax(store_profit)
lowest_store_index = np.argmin(store_profit)

# Most and least profitable categories
most_profitable_category_index = np.argmax(category_profit)
lowest_profit_category_index = np.argmin(category_profit)

# Expansion stores
expansion_stores = stores[eligible_for_expansion]


print("\nMANAGEMENT RECOMMENDATIONS")
print("==========================")

print("\nBEST-PERFORMING STORE")
print("---------------------")
print("Store:", stores[best_store_index])
print("Sales:", store_sales[best_store_index])
print("Cost:", store_cost[best_store_index])
print("Profit:", store_profit[best_store_index])
print(
    "Profit Margin:",
    round(store_margin[best_store_index], 2),
    "%"
)


print("\nLOWEST-PERFORMING STORE")
print("-----------------------")
print("Store:", stores[lowest_store_index])
print("Sales:", store_sales[lowest_store_index])
print("Cost:", store_cost[lowest_store_index])
print("Profit:", store_profit[lowest_store_index])
print(
    "Profit Margin:",
    round(store_margin[lowest_store_index], 2),
    "%"
)


print("\nMOST PROFITABLE CATEGORY")
print("------------------------")
print("Category:", categories[most_profitable_category_index])
print(
    "Sales:",
    category_sales[most_profitable_category_index]
)
print(
    "Cost:",
    category_cost[most_profitable_category_index]
)
print(
    "Profit:",
    category_profit[most_profitable_category_index]
)
print(
    "Profit Margin:",
    round(
        category_margin[most_profitable_category_index],
        2
    ),
    "%"
)


print("\nLOWEST-PROFIT CATEGORY")
print("----------------------")
print("Category:", categories[lowest_profit_category_index])
print(
    "Profit:",
    category_profit[lowest_profit_category_index]
)


print("\nEXPANSION RECOMMENDATIONS")
print("-------------------------")

if len(expansion_stores) > 0:
    for store in expansion_stores:
        print(store)
else:
    print("No stores are eligible.")


# ============================================================
# COST OPTIMIZATION
# ============================================================

# Find combinations with profit margin below 22%
combination_margin = (
    profit_data
    / sales_data
) * 100

low_margin = combination_margin < 22

print("\nCOST OPTIMIZATION")
print("-----------------")

found = False

for i, j in zip(*np.where(low_margin)):
    found = True
    print(
        "Store:",
        stores[i],
        "| Category:",
        categories[j],
        "| Cost:",
        cost_data[i, j],
        "| Profit Margin:",
        round(combination_margin[i, j], 2),
        "%"
    )

if not found:
    print("No combinations require cost optimization.")


# ============================================================
# INVENTORY REORDER
# ============================================================

reorder_required = closing_stock < reorder_level

print("\nINVENTORY REORDER")
print("-----------------")

found = False

for i, j in zip(*np.where(reorder_required)):
    found = True

    reorder_quantity = (
        reorder_level - closing_stock[i, j]
    )

    print(
        "Store:",
        stores[i],
        "| Category:",
        categories[j],
        "| Closing Stock:",
        closing_stock[i, j],
        "| Reorder Quantity:",
        reorder_quantity
    )

if not found:
    print("No inventory reorder required.")



SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: 11675000
Total Cost: 8600000
Total Profit: 3075000
Overall Profit Margin: 26.34 %
Average Transaction Value: 389166.67
Highest Individual Sales Value: 1050000
Lowest Individual Sales Value: 175000

STORE SUMMARY
-------------

Store: Bengaluru
Total Sales: 2270000
Total Cost: 1665000
Total Profit: 605000
Profit Margin: 26.65 %
Category Targets Achieved: 6
Total Units Sold: 2270
Expansion Eligibility: Not Eligible

Store: Hyderabad
Total Sales: 2295000
Total Cost: 1685000
Total Profit: 610000
Profit Margin: 26.58 %
Category Targets Achieved: 4
Total Units Sold: 2295
Expansion Eligibility: Not Eligible

Store: Chennai
Total Sales: 2310000
Total Cost: 1710000
Total Profit: 600000
Profit Margin: 25.97 %
Category Targets Achieved: 4
Total Units Sold: 2310
Expansion Eligibility: Not Eligible

Store: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000
Profit Margin: 26.77 %
Category Targets Ac